### PR TITLE
Add type alias for indexed natural transformation

### LINKED ISSUE #22: Add Indexed version of a Natural Transformation
Something simple like
```purescript
module Data.Indexed.NaturalTransformation where

type IndexedNaturalTransformation m n = forall x y a. m x y a -> n x y a

infixr 4 type IndexedNaturalTransformation as ~~>
```

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #22

### CODE REVIEW

**Comment by JordanMartinez** [comment]
@garyb Do you want to include this, too? Maybe the alias should be something different (e.g. `:~>`)?

**Comment by JordanMartinez** [comment]
@garyb Any thoughts on this PR? It's been open for a while.

**Comment by garyb** [comment]
I don't really see much use for it, to be honest. Maybe I'm wrong? I've become less enamoured with the normal `~>` too though, since I often find I end up needing to change `f ~> g` to `forall a. f a -> g (Maybe a)` to and things like that which means it gets in the way :smile:.

**Comment by JordanMartinez** [comment]
Nah, I agree. `~>` does get in the way at various times.

**Pull request closed without merging**
